# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=255)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
    ]
