# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170324_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='nummadekochi/media'),
        ),
    ]
