# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170325_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
