# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170326_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donateitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('donor', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
