# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170326_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
